### ISSUE TITLE
update to QT5

### ISSUE THREAD

**Issue by miramikes** [antanasbruzas/abGate#1]
Hello,

there is ongoing process in debian - removing QT4 from debian archive.
Is there any chance get Abgate builded against QT5?

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=874806

best regards

mira

**Comment by antanasbruzas** [comment]
Hi,
I'll take a look at this in the following week. Thanks for reporting

**Comment by antanasbruzas** [comment]
Please try using new version for Qt5 https://github.com/antanasbruzas/abGate/releases/tag/v1.1.9
I was able to build and use it on Debian GNU/Linux 9 (4.9.0-4-rt-amd64 #1 SMP PREEMPT RT Debian 4.9.51-1 (2017-09-28) x86_64 GNU/Linux)
